#!/usr/bin/python
#
# Knot-specific key destructor in PKCS #11
# using the "keymgr" utility.  See its help
# output for operational controls.
#
# Note that keymgr permits keys to be generated
# before a zone is known to Knot DNS.
#
# This process has interactions with ods-zonedata-recv-knot.py
# to add and remove zone data orthogonally, in spite of
# Knot DNS resisting such an approach.  The opposite of this
# file's operation is found in ods-keyops-knot-addkey.
#
# From: Rick van Rein <rick@openfortress.nl>


import os
import sys


import rabbitdnssec
from rabbitdnssec import log_debug, log_info, log_notice, log_warning, log_error, log_critical


# Parse commandline arguments
try:
	[_me,zone,keyid] = sys.argv
except:
	sys.stderr.write ('Usage: ' + sys.argv [0] + ' zone keyid\n')
	sys.exit (1)


def dnssec_strip (zone):
	# If a zone file exists, remove its DNSSEC data, meaning the
	# DNSKEY, NSEC/3 and RRSIG records.  This is done by setting
	# the zone to the unsigned input zone.  As a slight complication
	# (cough) we need to retain SOA serial numbering, so we do it
	# through ldns-zonediff with its options -S, -K and -N to pull
	# RRSIG, DNSKEY and NSEC/3 records into the comparison.
	#
	# Return zero on success; this is used in dnssec_disable.
	# Aim is to be atomic; non-zero return for complete inaction.
	#
	# This function assumes to run only once at the same time;
	# this is assured when run under Knot DNS's conf-begin.
	#
	signedzonefile = '/tmp/dnssec_strip.zone'  # we need a name...
	presigzonefile = '/var/opendnssec/unsigned/' + zone + '.txt'
	rv0 = os.system ('knotc zone-begin "' + zone + '"')
	rv1 = 0
	rv2 = 0
	if rv0==0:
		log_debug ('knotc zone-read "' + zone + '" | sed \'s/^\[[^]]*\] *//\'' + ' > "' + signedzonefile + '"')
		rv1 = os.system ('knotc zone-read "' + zone + '" | sed \'s/^\[[^]]*\] *//\'' + ' > "' + signedzonefile + '"')
	if rv0==0 and rv1==0:
		rv2 = os.system ('ldns-zonediff -k -S -K -N -o "' + zone + '" "' + signedzonefile + '" "' + presigzonefile + '" | knotc')
	try:
		pass #TODO#DEBUG# os.unlink (signedzonefile)
	except:
		pass
	if rv0==0 and rv1==0 and rv2==0:
		log_debug ('Succeeded with rv0 ==', rv0)
		log_debug ('knotc zone-commit "' + zone + '"')
		if os.system ('knotc zone-commit "' + zone + '"'):
			log_error ('Failed to commit ' + zone + '; liberally assuming empty update which would upset Knot DNS...')
			log_error ('knotc zone-abort "' + zone + '"')
			os.system ('knotc zone-abort "' + zone + '"')
		retval = 0
	else:
		log_error ('Failing with rv0 ==', rv0)
		if rv0==0:
			log_debug ('knotc zone-abort "' + zone + '"')
			os.system ('knotc zone-abort "' + zone + '"')
		#TODO# Report that Knot DNS could not strip DNSSEC records
		log_error ('Knot DNS could not strip DNSSEC records for', zone, '(%d,%d,%d)' % (rv0,rv1,rv2))
		retval = 1
	return retval

def dnssec_disable (zone):
	# Ensure that a zone is no longer served with DNSSEC.
	# If the zone is no longer in existence, there is no
	# work to be done and this function succeeds (as there
	# is no longer a dependency on keys that have gone).
	#
	# Note: Zone data is removed orthogonally; when the zone file
	# continues to exist then Knot DNS will continue to serve the
	# zone file, but without signatures.  We must however take
	# action to remove these signatures and NSEC/3 data.
	#
	rv0 = os.system ('knotc conf-begin')
	rv1 = 0
	rv2 = 0
	if rv0==0:
		# Try to unset the zone property dnssec-signing; accept failure
		#
		# Note how silly: conf-get will return without error but unset
		# will report an error when a feature was previously unknown!
		rv1 = os.system ('knotc conf-unset "zone[' + zone + '].dnssec-signing"')
		if rv1 != 0:
			rv1 = 0
	if rv0==0 and rv1==0:
		rv2 = dnssec_strip (zone)
	if rv0==0 and rv1==0 and rv2==0:
		os.system ('knotc conf-commit')
	else:
		if rv0==0:
			os.system ('knotc conf-abort')
		#TODO# Report that Knot DNS could not disable DNSSEC
		log_error ('Knot DNS could not disable DNSSEC for', zone, '(%d,%d,%d)' % (rv0,rv1,rv2))


print 'CMD> keymgr -C /var/lib/knot/confdb ' + zone + ' delete ' + keyid
status = os.system ('keymgr -C /var/lib/knot/confdb ' + zone + ' delete ' + keyid)
if status != 0:
	log_error ('Failed to delete key ' + keyid + ' for zone ', zone)
	log_error ('In spite of lingering key, disabling DNSSEC for zone', zone)

# disable DNSSEC and strip the zone while at it
dnssec_disable (zone)

sys.exit (os.WEXITSTATUS (status))

