#!/usr/bin/env python
#
# ods-rsync-zonedata-wrapper -- Wrapper around RSync for zonedata uploads
#
# This is a very simple script that wraps around RSync, running as a server,
# usually from an SSH account's authorized_keys.  The wrapper notifies a daemon
# listening to the indicated fifo that a new version of the zonedata has been
# uploaded.
#
# From: Rick van Rein <rick@openfortress.nl>


import os

import rabbitdnssec
from rabbitdnssec import log_debug, log_info, log_notice, log_warning, log_error, log_critical

cfg = rabbitdnssec.my_config ('ods-rsync-zonedata')
upload_dir = cfg ['upload_dir']
trigger_fifo = cfg ['trigger_fifo']

# /usr/bin/rsync --server --sender -vlogDtprCz . /home/portal/upload
os.system ('/usr/bin/rsync --fake-super --server -vdc --delete . "' + upload_dir + '"')
os.system ('cp "' + upload_dir + '/../keep_me/"* "' + upload_dir + '"')

try:
	kick = os.open (trigger_fifo, os.O_WRONLY | os.O_NONBLOCK)
	os.write (kick,'KICK\n')
	os.close (kick)
except OSError, ioe:
	if ioe.errno == 6:
		log_notice ('There is no listening ods-rsync-zonedata daemon; skipping notification for new data')
	else:
		raise

