#!/usr/bin/env python
#
# ods-rsync-zonedata-wrapper -- Wrapper around RSync for zonedata uploads
#
# This is a very simple script that wraps around RSync, running as a server,
# usually from an SSH account's authorized_keys.  The wrapper notifies a daemon
# listening to the indicated fifo that a new version of the zonedata has been
# uploaded.
#
# From: Rick van Rein <rick@openfortress.nl>


import os

import rabbitdnssec

cfg = rabbitdnssec.my_config ('ods-rsync-zonedata')
upload_dir = cfg ['upload_dir']
trigger_fifo = cfg ['trigger_fifo']

# /usr/bin/rsync --server --sender -vlogDtprCz . /home/portal/upload
os.system ('/usr/bin/rsync --fake-super --server -vdc --delete . "' + upload_dir + '"')

open (trigger_fifo, 'w').write ('KICK\n')


