#!/usr/bin/env python
#
# ods-zonedata-recv -- Receive from the zonedata queue, finding empty to delete
#
# This program takes delivery of complete zone files in a queue named
# $HOST_zonedata and stores it in the filesystem through a backend that
# depends on the locally used DNSSEC signing software.
#
# When the received zone data is an empty string, then the reverse will be
# done, to clean up after the zone.
#
# From: Rick van Rein <rick@openfortress.nl>


import os
import sys
import time
import socket
import ssl
import re

import dns
import dns.zone

import pika

import rabbitdnssec
from rabbitdnssec import log_debug, log_info, log_notice, log_warning, log_error, log_critical


# Setup from configuration variables
#
queuename               = rabbitdnssec.my_queue ('zonedata')
singer_exchange_name    = rabbitdnssec.my_exchange ()
parenting_exchange_name = rabbitdnssec.my_exchange ('parenting')
backend                 = rabbitdnssec.my_backend ()
backendmod              = rabbitdnssec.my_backendmod ('ods-zonedata-recv-',
					ovr_appname='ods-zonedata')


# The regular expression of considered-proper zone names
#
zone_re = re.compile ('^[-a-z0-9]+(\.[-a-z0-9]+){1,}$')


def try_unlink (path):
	try:
		os.unlink (path)
	except:
		pass

def soa_serial (zdata, zname):
	rd = zdata.find_rdataset ('@', dns.rdatatype.SOA)
	if len (rd) != 1:
		raise dns.zone.NoSOA ('Number of SOA records in zone apex is not one')
	return rd [0].serial

def process_msg (chan, mth, props, body):
	zone = '<unavailable>'
	ok = True
	try:
		# log_debug ('Fetching subject from', props.headers)
		zone = props.headers ['subject'].lower ()
		# log_debug ('Fetched  subject', zone)
		if body == '':
			log_info ('Removing zonedata and zonelist entry for', zone)
			# remove zonelist entry
			backendmod.delzone (zone)
			#TODO# DEPRECATED -- # stop signing the zone
			#TODO# DEPRECATED -- os.system ('ods-signer clear ' + zone)
			# remove the zone data files
			try_unlink ('/var/opendnssec/unsigned/' + zone + '.txt')
			try_unlink ('/var/opendnssec/uploaded/' + zone + '.txt')
		else:
			log_debug ('Parsing', len (body), 'bytes for', zone)
			try:
				# Let's give way to an $ORIGIN -- if one exists
				# log_debug ('Trying under $ORIGIN assumption')
				zdnew = dns.zone.from_text (body, origin=None)
				# log_debug ('Did not fail on $ORIGIN assumption')
				zone = zdnew.origin.to_text (omit_final_dot=True)
				# log_debug ('Found $ORIGIN to be', zone)
			except dns.zone.UnknownOrigin:
				# Fallback to the subject/filename as zone name
				# log_debug ('Trying with $ORIGIN set to', zone)
				zdnew = dns.zone.from_text (body, origin=zone)
				# log_debug ('Did not fail with $ORIGIN set to', zone)
			# except NoSOA --> missing SOA record (caught/reported below)
			# except NoNS  --> missing NS records (caught/reported below)
			if zone_re.match (zone) is None:
				raise Exception ('Invalid zone name syntax for ' + zone)
			try:
				have_old = True
				zdold = dns.zone.from_file ('/var/opendnssec/uploaded/' + zone + '.txt', origin=zone, allow_include=False)
				# log_debug ('Loaded old version of', zone)
				soa_old = soa_serial (zdold, zone)
				soa_new = soa_serial (zdnew, zone)
				log_debug ('Request to migrate SOA serial for', zone, 'from', soa_old, 'to', soa_new)
				if soa_old >= soa_new:
					# log_warning ('SOA serial ' + str (soa_new) + ' ignored; already got ' + str (soa_old))
					raise Exception ('SOA serial ' + str (soa_new) + ' ignored; already got ' + str (soa_old))
			except IOError, ioe:
				# No old file, it seems.  Do not check SOA
				have_old = False
			# save body to new zonefile -- but not in un/signed yet
			zdnew.to_file ('/var/opendnssec/uploaded/' + zone + '.new')
			# atomically replace the zonefile in uploaded
			os.rename ('/var/opendnssec/uploaded/' + zone + '.new',
			           '/var/opendnssec/uploaded/' + zone + '.txt')
			# have zonelist entry
			if not have_old:
				log_info ('Adding zonedata and zonelist entry for', zone)
				backendmod.addzone (zone)
			#TODO# DEPRECATED -- generate composite zone by adding parenting data
			#TODO# DEPRECATED -- os.system ('ods-zonedata-unsigned ' + zone)
			#TODO# DEPRECATED -- instead send a message to the parenting exchange
			# generate composite zone by hinting the parenting exchange
		log_debug ('Hinting parenting exchange about', zone)
		chan.basic_publish (exchange=parenting_exchange_name,
					routing_key='',
					body=zone)
		# Update .signconf, creating or deleting as per zonelist.xml
		if backend == 'opendnssec':
			os.system ('./ods-zonedata-signconf ' + zone)
	except dns.zone.NoSOA:
		log_error ('No SOA records found in', zone)
	except dns.zone.NoNS:
		log_error ('No NS records found in', zone)
	except Exception, e:
		log_error ('Exception:', e, 'for zone', zone)
		ok = False
	if not ok:
		log_error ('Failure while processing zonedata for ' + zone)
		chan.basic_nack (delivery_tag=mth.delivery_tag, requeue=False)
		#TODO#STILL_WANT_TO_CONTINUE# chan.tx_rollback ()
		chan.tx_commit ()
	else:
		log_info ('Successfully processed zonedata update for ' + zone)
		chan.basic_ack  (delivery_tag=mth.delivery_tag)
		chan.tx_commit ()
		#TODO# signal parent/child system about updated zonedata

creds = rabbitdnssec.my_credentials ()
cnxparm = rabbitdnssec.my_connectionparameters (creds)

cnx = None
chan = None
try:
	cnx = pika.BlockingConnection (cnxparm)
	chan = cnx.channel ()
	chan.basic_consume (process_msg, queue=queuename)
	chan.tx_select ()
	chan.start_consuming ()
except pika.exceptions.AMQPChannelError, e:
	log_error ('AMQP Channel Error:', e)
	sys.exit (1)
except pika.exceptions.AMQPError, e:
	log_error ('AMQP Error:', e)
	sys.exit (1)
finally:
	if chan is not None:
		chan.tx_rollback ()
		chan = None
	if cnx is not None:
		cnx.close ()
	cnx = None

sys.exit (0)
