#!/usr/bin/env python
#
# Send a hint about the given zone(s) to the parenting exchange.
# These hints ask to reload the zone data, append any name server
# records, and consider triggering the process of signing the zone.
#
# From: Rick van Rein <rick@openfortress.nl>


import os
import sys
import socket
import ssl

import pika

import rabbitdnssec


# Some configuration settings
#
queue_name = rabbitdnssec.my_queue ('zonekeys')
exchange_name = rabbitdnssec.my_exchange ('parenting')


#
# Check the command line.
#

if len (sys.argv) < 2:
	sys.stderr.write ('Usage: ' + sys.argv [0] + ' zone...\n')
	sys.exit (1)
#
# Have the queueing infrastructure for the parent exchange.
#

#TODO# really use the parenting account here?
creds   = rabbitdnssec.my_credentials (ovr_username='parenting')
cnxparm = rabbitdnssec.my_connectionparameters (creds)
print 'Connection parameters:', cnxparm
cnx = None
chan = None
try:
	cnx = pika.BlockingConnection (cnxparm)
	chan = cnx.channel ()
	#TODO:CLASS# chan.basic_consume (process_msg, queue=queue_name)
	#TODO:NOTHERE# print 'Starting transaction'
	#TODO:NOTHERE# chan.tx_select ()
	#TODO:CLASS# print 'Basically consuming!'
	#TODO:CLASS# chan.start_consuming ()
	#TODO:CLASS# print 'Done consuming; committing transaction'
except pika.exceptions.AMQPChannelError, e:
	print 'AMQP Channel Error:', e
	sys.exit (1)
except pika.exceptions.AMQPError, e:
	print 'AMQP Error:', e
	sys.exit (1)
#TODO:BELOW# finally:
#TODO:BELOW# 	if chan is not None:
#TODO:BELOW# 		#TODO:NOTHERE# chan.tx_rollback ()
#TODO:BELOW# 		chan = None
#TODO:BELOW# 	if cnx is not None:
#TODO:BELOW# 		cnx.close ()
#TODO:BELOW# 	cnx = None



#
# Now have the queue for hints about uploaded zones, sent to the exchange.
#

#STATIC# chan.queue_declare (queue=queue_name,
#STATIC# 		durable=True,
#STATIC# 		exclusive=False,
#STATIC# 		auto_delete=False)
#STATIC# chan.queue_bind (exchange=exchange_name,
#STATIC# 		queue=queue_name,
#STATIC# 		routing_key='')

#
# Finally send the hints for the given zone name(s) in cmdline arguments.
#
for zone in sys.argv [1:]:
	sys.stdout.write ('Hinting for ' + zone + '...')
	sys.stdout.flush ()
	chan.basic_publish (exchange=exchange_name,
			routing_key='',
			body=zone)
	sys.stdout.write (' done\n')

#
# Close down and cleanup.
#
chan = None
cnx.close ()
cnx = None
